name: deploy_release
on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Checkout ilw-hero
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-hero'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-back-to-top
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-back-to-top'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-content
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-content'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-page
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-page'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-columns
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-columns'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout ilw-grid
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/ilw-grid'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: Checkout toolkit management
      uses: actions/checkout@v4
      with:
        repository: 'web-illinois/toolkit-management'
        ref: 'main'
        path: './external-directory'
    - run: cp ./external-directory/global-css/builder/*.json ./site/imported_json/components
    - run: cp ./external-directory/global-css/builder/versions/*.json ./site/imported_json/component_versions
    - run: rm -r ./external-directory

    - name: NPM Install
      run: npm install
    - run: npm rebuild
    - run: npm run-script build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ vars.TOOLKIT_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.TOOLKIT_AWS_ACCESS_SECRET }}
        aws-region: us-east-2

    - name: Deploy examples to S3 bucket 
      run: aws s3 sync ./_site/ s3://builder3.toolkit.illinois.edu/content --delete --acl bucket-owner-full-control
    - name: Invalidate Cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id	EJE7H24JF0N2G --paths "/*"
